#!/bin/sh

APP=chromium-bsu

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget -q https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/tools/pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: chromium-bsu
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.debian.org/debian/ stable main contrib non-free
  packages:
    - chromium-bsu" >> recipe.yml;



./pkg2appimage ./recipe.yml;

ARCH=x86_64 ./appimagetool --comp zstd --mksquashfs-opt -Xcompression-level --mksquashfs-opt 20 ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./;
chmod a+x ./$APP

rm -R -f ./tmp
