#!/bin/sh

APP=chromium-bsu

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget -q "$(wget -q https://api.github.com/repos/probonopd/go-appimage/releases -O - | sed 's/"/ /g; s/ /\n/g' | grep -o 'https.*continuous.*tool.*86_64.*mage$')" -O appimagetool
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/tools/pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: chromium-bsu
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.debian.org/debian/ stable main contrib non-free
  packages:
    - chromium-bsu" >> recipe.yml;



./pkg2appimage ./recipe.yml;

ARCH=x86_64 VERSION=$(./appimagetool -v | grep -o '[[:digit:]]*') ./appimagetool -s ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./;
chmod a+x ./$APP

rm -R -f ./tmp
