#!/bin/sh

APP=chromium-bsu

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget -q $(wget -q https://api.github.com/repos/probonopd/go-appimage/releases -O - | grep -v zsync | grep -i continuous | grep -i appimagetool | grep -i x86_64 | grep browser_download_url | cut -d '"' -f 4 | head -1) -O appimagetool
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/tools/pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: chromium-bsu
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.debian.org/debian/ stable main contrib non-free
  packages:
    - chromium-bsu" >> recipe.yml;



./pkg2appimage ./recipe.yml;

ARCH=x86_64 VERSION=$(./appimagetool -v | grep -o '[[:digit:]]*') ./appimagetool -s ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./;
chmod a+x ./$APP

rm -R -f ./tmp
