#!/bin/sh

APP=filezilla-server

export ARCH="x86_64"

# DEPENDENCIES

dependencies="tar"
for d in $dependencies; do
	if ! command -v "$d" 1>/dev/null; then
		echo "ERROR: missing command \"d\", install the above and retry" && exit 1
	fi
done

_appimagetool() {
	if ! command -v appimagetool 1>/dev/null; then
		[ ! -f ./appimagetool ] && echo " Downloading appimagetool..." && curl -#Lo appimagetool https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-"$ARCH".AppImage && chmod a+x ./appimagetool
		./appimagetool "$@"
	else
		appimagetool "$@"
	fi
}

# CREATE DIRECTORIES
mkdir -p "tmp/$APP".AppDir && cd tmp || exit 1

################################################################################################################################################################
#				BUILD
################################################################################################################################################################

PKG_URL=$(curl -Ls https://sourceforge.net/projects/fabiololix-os-archive/files/src/ | tr ' ><"' '\n' | grep -i "^http.*linux.*tar" | head -1)
VERSION=$(echo "$PKG_URL" | tr '_' '\n' | grep "^[0-9].*.[0-9]" | head -1)

[ -z "$VERSION" ] && exit 0

if [ ! -f ./*tar.xz ]; then
	curl -#Lo FileZilla.tar.xz "$PKG_URL" || exit 1
	tar xf ./*tar.xz
fi

cp -r ./F*/* "$APP".AppDir/

################################################################################################################################################################
#				COMMON
################################################################################################################################################################

# APPRUN
rm -f "$APP".AppDir/AppRun
cat >> "$APP".AppDir/AppRun << 'EOF'
#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"

export PATH="${HERE}"/bin/:"${PATH}"
export LD_LIBRARY_PATH="${HERE}"/lib/:"${LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}"/share/:"${XDG_DATA_DIRS}"

case "$1" in
  '') "${HERE}"/bin/filezilla-server-gui "$@";;
  *) "${HERE}"/bin/filezilla-server "$@";;
esac

EOF
chmod a+x "$APP".AppDir/AppRun

# LAUNCHER
echo "[Desktop Entry]
Name=FileZilla
GenericName=FTP client
GenericName[da]=FTP-klient
GenericName[de]=FTP-Client
GenericName[fr]=Client FTP
Comment=Download and upload files via FTP, FTPS and SFTP
Comment[da]=Download og upload filer via FTP, FTPS og SFTP
Comment[de]=Dateien über FTP, FTPS und SFTP übertragen
Comment[fr]=Transférer des fichiers via FTP, FTPS et SFTP
Exec=filezilla-server-gui
Terminal=false
Icon=filezilla
Type=Application
Categories=Network;FileTransfer;
Version=1.0" > "$APP".AppDir/*.desktop

# ICON
cp -r "$APP".AppDir/share/icons/hicolor/256x256/apps/* "$APP".AppDir/"$APP".png || exit 1

# CONVERT THE APPDIR TO AN APPIMAGE

APPNAME=$(cat "$APP".AppDir/*.desktop | grep '^Name=' | head -1 | cut -c 6- | sed 's/ /-/g')
REPO="Database-of-pkg2appimaged-packages"
TAG="filezilla-server"
UPINFO="gh-releases-zsync|$GITHUB_REPOSITORY_OWNER|$REPO|$TAG|*x86_64.AppImage.zsync"

ARCH=x86_64 _appimagetool -u "$UPINFO" \
	./"$APP".AppDir "$APPNAME"-Server_"$VERSION"-x86_64.AppImage

if ! test -f ./*.AppImage; then
	echo "No AppImage available."; exit 1
fi
cd .. && mv ./tmp/*.AppImage* . && chmod a+x ./*.AppImage || exit 1
